# Generated by Django 2.1.7 on 2019-03-14 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
